// Code generated by protoc-gen-go.
// source: servers.proto
// DO NOT EDIT!

package servers

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SessionData struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SessionData) Reset()         { *m = SessionData{} }
func (m *SessionData) String() string { return proto.CompactTextString(m) }
func (*SessionData) ProtoMessage()    {}

func (m *SessionData) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *SessionData) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type SessionInfo struct {
	Address          *uint32        `protobuf:"varint,1,opt,name=address" json:"address,omitempty"`
	Port             *int32         `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Npid             *uint64        `protobuf:"fixed64,3,opt,name=npid" json:"npid,omitempty"`
	Players          *int32         `protobuf:"varint,4,opt,name=players" json:"players,omitempty"`
	Maxplayers       *int32         `protobuf:"varint,5,opt,name=maxplayers" json:"maxplayers,omitempty"`
	Data             []*SessionData `protobuf:"bytes,6,rep,name=data" json:"data,omitempty"`
	Sid              *uint64        `protobuf:"varint,7,opt,name=sid" json:"sid,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SessionInfo) Reset()         { *m = SessionInfo{} }
func (m *SessionInfo) String() string { return proto.CompactTextString(m) }
func (*SessionInfo) ProtoMessage()    {}

func (m *SessionInfo) GetAddress() uint32 {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return 0
}

func (m *SessionInfo) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *SessionInfo) GetNpid() uint64 {
	if m != nil && m.Npid != nil {
		return *m.Npid
	}
	return 0
}

func (m *SessionInfo) GetPlayers() int32 {
	if m != nil && m.Players != nil {
		return *m.Players
	}
	return 0
}

func (m *SessionInfo) GetMaxplayers() int32 {
	if m != nil && m.Maxplayers != nil {
		return *m.Maxplayers
	}
	return 0
}

func (m *SessionInfo) GetData() []*SessionData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SessionInfo) GetSid() uint64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

type ServersCreateSessionMessage struct {
	Info             *SessionInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ServersCreateSessionMessage) Reset()         { *m = ServersCreateSessionMessage{} }
func (m *ServersCreateSessionMessage) String() string { return proto.CompactTextString(m) }
func (*ServersCreateSessionMessage) ProtoMessage()    {}

func (m *ServersCreateSessionMessage) GetInfo() *SessionInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ServersCreateSessionResultMessage struct {
	Result           *int32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Sessionid        *uint64 `protobuf:"fixed64,2,opt,name=sessionid" json:"sessionid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServersCreateSessionResultMessage) Reset()         { *m = ServersCreateSessionResultMessage{} }
func (m *ServersCreateSessionResultMessage) String() string { return proto.CompactTextString(m) }
func (*ServersCreateSessionResultMessage) ProtoMessage()    {}

func (m *ServersCreateSessionResultMessage) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *ServersCreateSessionResultMessage) GetSessionid() uint64 {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return 0
}

type ServersGetSessionsMessage struct {
	Infos            []*SessionData `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ServersGetSessionsMessage) Reset()         { *m = ServersGetSessionsMessage{} }
func (m *ServersGetSessionsMessage) String() string { return proto.CompactTextString(m) }
func (*ServersGetSessionsMessage) ProtoMessage()    {}

func (m *ServersGetSessionsMessage) GetInfos() []*SessionData {
	if m != nil {
		return m.Infos
	}
	return nil
}

type ServersGetSessionsResultMessage struct {
	Servers          []*SessionInfo `protobuf:"bytes,1,rep,name=servers" json:"servers,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ServersGetSessionsResultMessage) Reset()         { *m = ServersGetSessionsResultMessage{} }
func (m *ServersGetSessionsResultMessage) String() string { return proto.CompactTextString(m) }
func (*ServersGetSessionsResultMessage) ProtoMessage()    {}

func (m *ServersGetSessionsResultMessage) GetServers() []*SessionInfo {
	if m != nil {
		return m.Servers
	}
	return nil
}

type ServersUpdateSessionMessage struct {
	Sessionid        *uint64      `protobuf:"fixed64,1,opt,name=sessionid" json:"sessionid,omitempty"`
	Info             *SessionInfo `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ServersUpdateSessionMessage) Reset()         { *m = ServersUpdateSessionMessage{} }
func (m *ServersUpdateSessionMessage) String() string { return proto.CompactTextString(m) }
func (*ServersUpdateSessionMessage) ProtoMessage()    {}

func (m *ServersUpdateSessionMessage) GetSessionid() uint64 {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return 0
}

func (m *ServersUpdateSessionMessage) GetInfo() *SessionInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ServersUpdateSessionResultMessage struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ServersUpdateSessionResultMessage) Reset()         { *m = ServersUpdateSessionResultMessage{} }
func (m *ServersUpdateSessionResultMessage) String() string { return proto.CompactTextString(m) }
func (*ServersUpdateSessionResultMessage) ProtoMessage()    {}

func (m *ServersUpdateSessionResultMessage) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type ServersDeleteSessionMessage struct {
	Sessionid        *uint64 `protobuf:"fixed64,1,opt,name=sessionid" json:"sessionid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServersDeleteSessionMessage) Reset()         { *m = ServersDeleteSessionMessage{} }
func (m *ServersDeleteSessionMessage) String() string { return proto.CompactTextString(m) }
func (*ServersDeleteSessionMessage) ProtoMessage()    {}

func (m *ServersDeleteSessionMessage) GetSessionid() uint64 {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return 0
}

type ServersDeleteSessionResultMessage struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ServersDeleteSessionResultMessage) Reset()         { *m = ServersDeleteSessionResultMessage{} }
func (m *ServersDeleteSessionResultMessage) String() string { return proto.CompactTextString(m) }
func (*ServersDeleteSessionResultMessage) ProtoMessage()    {}

func (m *ServersDeleteSessionResultMessage) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func init() {
}
