// Code generated by protoc-gen-go.
// source: auth.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type AuthenticateWithKeyMessage struct {
	LicenseKey       *string `protobuf:"bytes,1,req,name=licenseKey" json:"licenseKey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthenticateWithKeyMessage) Reset()         { *m = AuthenticateWithKeyMessage{} }
func (m *AuthenticateWithKeyMessage) String() string { return proto.CompactTextString(m) }
func (*AuthenticateWithKeyMessage) ProtoMessage()    {}

func (m *AuthenticateWithKeyMessage) GetLicenseKey() string {
	if m != nil && m.LicenseKey != nil {
		return *m.LicenseKey
	}
	return ""
}

type AuthenticateWithDetailsMessage struct {
	Username         *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthenticateWithDetailsMessage) Reset()         { *m = AuthenticateWithDetailsMessage{} }
func (m *AuthenticateWithDetailsMessage) String() string { return proto.CompactTextString(m) }
func (*AuthenticateWithDetailsMessage) ProtoMessage()    {}

func (m *AuthenticateWithDetailsMessage) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *AuthenticateWithDetailsMessage) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type AuthenticateWithTokenMessage struct {
	Token            []byte `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AuthenticateWithTokenMessage) Reset()         { *m = AuthenticateWithTokenMessage{} }
func (m *AuthenticateWithTokenMessage) String() string { return proto.CompactTextString(m) }
func (*AuthenticateWithTokenMessage) ProtoMessage()    {}

func (m *AuthenticateWithTokenMessage) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type AuthenticateResultMessage struct {
	Result           *int32  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	Npid             *uint64 `protobuf:"fixed64,2,req,name=npid" json:"npid,omitempty"`
	SessionToken     []byte  `protobuf:"bytes,3,req,name=sessionToken" json:"sessionToken,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthenticateResultMessage) Reset()         { *m = AuthenticateResultMessage{} }
func (m *AuthenticateResultMessage) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResultMessage) ProtoMessage()    {}

func (m *AuthenticateResultMessage) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *AuthenticateResultMessage) GetNpid() uint64 {
	if m != nil && m.Npid != nil {
		return *m.Npid
	}
	return 0
}

func (m *AuthenticateResultMessage) GetSessionToken() []byte {
	if m != nil {
		return m.SessionToken
	}
	return nil
}

type AuthenticateUserGroupMessage struct {
	GroupID          *int32 `protobuf:"varint,1,req,name=groupID" json:"groupID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AuthenticateUserGroupMessage) Reset()         { *m = AuthenticateUserGroupMessage{} }
func (m *AuthenticateUserGroupMessage) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserGroupMessage) ProtoMessage()    {}

func (m *AuthenticateUserGroupMessage) GetGroupID() int32 {
	if m != nil && m.GroupID != nil {
		return *m.GroupID
	}
	return 0
}

type AuthenticateValidateTicketMessage struct {
	ClientIP         *uint32 `protobuf:"fixed32,1,req,name=clientIP" json:"clientIP,omitempty"`
	Npid             *uint64 `protobuf:"fixed64,2,req,name=npid" json:"npid,omitempty"`
	Ticket           []byte  `protobuf:"bytes,3,req,name=ticket" json:"ticket,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthenticateValidateTicketMessage) Reset()         { *m = AuthenticateValidateTicketMessage{} }
func (m *AuthenticateValidateTicketMessage) String() string { return proto.CompactTextString(m) }
func (*AuthenticateValidateTicketMessage) ProtoMessage()    {}

func (m *AuthenticateValidateTicketMessage) GetClientIP() uint32 {
	if m != nil && m.ClientIP != nil {
		return *m.ClientIP
	}
	return 0
}

func (m *AuthenticateValidateTicketMessage) GetNpid() uint64 {
	if m != nil && m.Npid != nil {
		return *m.Npid
	}
	return 0
}

func (m *AuthenticateValidateTicketMessage) GetTicket() []byte {
	if m != nil {
		return m.Ticket
	}
	return nil
}

type AuthenticateValidateTicketResultMessage struct {
	Result           *int32  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	Npid             *uint64 `protobuf:"fixed64,2,req,name=npid" json:"npid,omitempty"`
	GroupID          *int32  `protobuf:"varint,3,req,name=groupID" json:"groupID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthenticateValidateTicketResultMessage) Reset() {
	*m = AuthenticateValidateTicketResultMessage{}
}
func (m *AuthenticateValidateTicketResultMessage) String() string { return proto.CompactTextString(m) }
func (*AuthenticateValidateTicketResultMessage) ProtoMessage()    {}

func (m *AuthenticateValidateTicketResultMessage) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *AuthenticateValidateTicketResultMessage) GetNpid() uint64 {
	if m != nil && m.Npid != nil {
		return *m.Npid
	}
	return 0
}

func (m *AuthenticateValidateTicketResultMessage) GetGroupID() int32 {
	if m != nil && m.GroupID != nil {
		return *m.GroupID
	}
	return 0
}

type AuthenticateKickUserMessage struct {
	Npid             *uint64 `protobuf:"fixed64,1,req,name=npid" json:"npid,omitempty"`
	Reason           *int32  `protobuf:"varint,2,req,name=reason" json:"reason,omitempty"`
	ReasonString     *string `protobuf:"bytes,3,req,name=reasonString" json:"reasonString,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthenticateKickUserMessage) Reset()         { *m = AuthenticateKickUserMessage{} }
func (m *AuthenticateKickUserMessage) String() string { return proto.CompactTextString(m) }
func (*AuthenticateKickUserMessage) ProtoMessage()    {}

func (m *AuthenticateKickUserMessage) GetNpid() uint64 {
	if m != nil && m.Npid != nil {
		return *m.Npid
	}
	return 0
}

func (m *AuthenticateKickUserMessage) GetReason() int32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

func (m *AuthenticateKickUserMessage) GetReasonString() string {
	if m != nil && m.ReasonString != nil {
		return *m.ReasonString
	}
	return ""
}

type AuthenticateExternalStatusMessage struct {
	Status           *int32 `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AuthenticateExternalStatusMessage) Reset()         { *m = AuthenticateExternalStatusMessage{} }
func (m *AuthenticateExternalStatusMessage) String() string { return proto.CompactTextString(m) }
func (*AuthenticateExternalStatusMessage) ProtoMessage()    {}

func (m *AuthenticateExternalStatusMessage) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

type AuthenticateRegisterServerMessage struct {
	ConfigPath       *string `protobuf:"bytes,1,opt,name=configPath" json:"configPath,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthenticateRegisterServerMessage) Reset()         { *m = AuthenticateRegisterServerMessage{} }
func (m *AuthenticateRegisterServerMessage) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRegisterServerMessage) ProtoMessage()    {}

func (m *AuthenticateRegisterServerMessage) GetConfigPath() string {
	if m != nil && m.ConfigPath != nil {
		return *m.ConfigPath
	}
	return ""
}

type AuthenticateRegisterServerResultMessage struct {
	Result           *int32  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	LicenseKey       *string `protobuf:"bytes,2,req,name=licenseKey" json:"licenseKey,omitempty"`
	ServerID         *int32  `protobuf:"varint,3,req,name=serverID" json:"serverID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthenticateRegisterServerResultMessage) Reset() {
	*m = AuthenticateRegisterServerResultMessage{}
}
func (m *AuthenticateRegisterServerResultMessage) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRegisterServerResultMessage) ProtoMessage()    {}

func (m *AuthenticateRegisterServerResultMessage) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *AuthenticateRegisterServerResultMessage) GetLicenseKey() string {
	if m != nil && m.LicenseKey != nil {
		return *m.LicenseKey
	}
	return ""
}

func (m *AuthenticateRegisterServerResultMessage) GetServerID() int32 {
	if m != nil && m.ServerID != nil {
		return *m.ServerID
	}
	return 0
}

func init() {
}
