// Code generated by protoc-gen-go.
// source: friends.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type FriendsSetSteamIDMessage struct {
	SteamID          *uint64 `protobuf:"fixed64,1,req,name=steamID" json:"steamID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FriendsSetSteamIDMessage) Reset()         { *m = FriendsSetSteamIDMessage{} }
func (m *FriendsSetSteamIDMessage) String() string { return proto.CompactTextString(m) }
func (*FriendsSetSteamIDMessage) ProtoMessage()    {}

func (m *FriendsSetSteamIDMessage) GetSteamID() uint64 {
	if m != nil && m.SteamID != nil {
		return *m.SteamID
	}
	return 0
}

type FriendsGetProfileDataMessage struct {
	Npids            []uint64 `protobuf:"fixed64,1,rep,name=npids" json:"npids,omitempty"`
	ProfileType      *string  `protobuf:"bytes,2,opt,name=profileType" json:"profileType,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FriendsGetProfileDataMessage) Reset()         { *m = FriendsGetProfileDataMessage{} }
func (m *FriendsGetProfileDataMessage) String() string { return proto.CompactTextString(m) }
func (*FriendsGetProfileDataMessage) ProtoMessage()    {}

func (m *FriendsGetProfileDataMessage) GetNpids() []uint64 {
	if m != nil {
		return m.Npids
	}
	return nil
}

func (m *FriendsGetProfileDataMessage) GetProfileType() string {
	if m != nil && m.ProfileType != nil {
		return *m.ProfileType
	}
	return ""
}

type ProfileDataResult struct {
	Npid             *uint64 `protobuf:"fixed64,1,opt,name=npid" json:"npid,omitempty"`
	Profile          []byte  `protobuf:"bytes,2,opt,name=profile" json:"profile,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProfileDataResult) Reset()         { *m = ProfileDataResult{} }
func (m *ProfileDataResult) String() string { return proto.CompactTextString(m) }
func (*ProfileDataResult) ProtoMessage()    {}

func (m *ProfileDataResult) GetNpid() uint64 {
	if m != nil && m.Npid != nil {
		return *m.Npid
	}
	return 0
}

func (m *ProfileDataResult) GetProfile() []byte {
	if m != nil {
		return m.Profile
	}
	return nil
}

type FriendsGetProfileDataResultMessage struct {
	Results          []*ProfileDataResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *FriendsGetProfileDataResultMessage) Reset()         { *m = FriendsGetProfileDataResultMessage{} }
func (m *FriendsGetProfileDataResultMessage) String() string { return proto.CompactTextString(m) }
func (*FriendsGetProfileDataResultMessage) ProtoMessage()    {}

func (m *FriendsGetProfileDataResultMessage) GetResults() []*ProfileDataResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type FriendDetails struct {
	Npid             *uint64 `protobuf:"fixed64,1,opt,name=npid" json:"npid,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FriendDetails) Reset()         { *m = FriendDetails{} }
func (m *FriendDetails) String() string { return proto.CompactTextString(m) }
func (*FriendDetails) ProtoMessage()    {}

func (m *FriendDetails) GetNpid() uint64 {
	if m != nil && m.Npid != nil {
		return *m.Npid
	}
	return 0
}

func (m *FriendDetails) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type FriendsRosterMessage struct {
	Friends          []*FriendDetails `protobuf:"bytes,1,rep,name=friends" json:"friends,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *FriendsRosterMessage) Reset()         { *m = FriendsRosterMessage{} }
func (m *FriendsRosterMessage) String() string { return proto.CompactTextString(m) }
func (*FriendsRosterMessage) ProtoMessage()    {}

func (m *FriendsRosterMessage) GetFriends() []*FriendDetails {
	if m != nil {
		return m.Friends
	}
	return nil
}

type FriendsPresence struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FriendsPresence) Reset()         { *m = FriendsPresence{} }
func (m *FriendsPresence) String() string { return proto.CompactTextString(m) }
func (*FriendsPresence) ProtoMessage()    {}

func (m *FriendsPresence) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *FriendsPresence) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type FriendsPresenceMessage struct {
	Friend           *uint64            `protobuf:"fixed64,1,req,name=friend" json:"friend,omitempty"`
	PresenceState    *int32             `protobuf:"varint,2,req,name=presenceState" json:"presenceState,omitempty"`
	CurrentServer    *uint64            `protobuf:"fixed64,3,opt,name=currentServer" json:"currentServer,omitempty"`
	Presence         []*FriendsPresence `protobuf:"bytes,4,rep,name=presence" json:"presence,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *FriendsPresenceMessage) Reset()         { *m = FriendsPresenceMessage{} }
func (m *FriendsPresenceMessage) String() string { return proto.CompactTextString(m) }
func (*FriendsPresenceMessage) ProtoMessage()    {}

func (m *FriendsPresenceMessage) GetFriend() uint64 {
	if m != nil && m.Friend != nil {
		return *m.Friend
	}
	return 0
}

func (m *FriendsPresenceMessage) GetPresenceState() int32 {
	if m != nil && m.PresenceState != nil {
		return *m.PresenceState
	}
	return 0
}

func (m *FriendsPresenceMessage) GetCurrentServer() uint64 {
	if m != nil && m.CurrentServer != nil {
		return *m.CurrentServer
	}
	return 0
}

func (m *FriendsPresenceMessage) GetPresence() []*FriendsPresence {
	if m != nil {
		return m.Presence
	}
	return nil
}

type FriendsSetPresenceMessage struct {
	Presence         []*FriendsPresence `protobuf:"bytes,1,rep,name=presence" json:"presence,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *FriendsSetPresenceMessage) Reset()         { *m = FriendsSetPresenceMessage{} }
func (m *FriendsSetPresenceMessage) String() string { return proto.CompactTextString(m) }
func (*FriendsSetPresenceMessage) ProtoMessage()    {}

func (m *FriendsSetPresenceMessage) GetPresence() []*FriendsPresence {
	if m != nil {
		return m.Presence
	}
	return nil
}

type FriendsGetUserAvatarMessage struct {
	Guid             *int32 `protobuf:"varint,2,req,name=guid" json:"guid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FriendsGetUserAvatarMessage) Reset()         { *m = FriendsGetUserAvatarMessage{} }
func (m *FriendsGetUserAvatarMessage) String() string { return proto.CompactTextString(m) }
func (*FriendsGetUserAvatarMessage) ProtoMessage()    {}

func (m *FriendsGetUserAvatarMessage) GetGuid() int32 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

type FriendsGetUserAvatarResultMessage struct {
	Result           *int32 `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	Guid             *int32 `protobuf:"varint,2,req,name=guid" json:"guid,omitempty"`
	FileData         []byte `protobuf:"bytes,3,req,name=fileData" json:"fileData,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FriendsGetUserAvatarResultMessage) Reset()         { *m = FriendsGetUserAvatarResultMessage{} }
func (m *FriendsGetUserAvatarResultMessage) String() string { return proto.CompactTextString(m) }
func (*FriendsGetUserAvatarResultMessage) ProtoMessage()    {}

func (m *FriendsGetUserAvatarResultMessage) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *FriendsGetUserAvatarResultMessage) GetGuid() int32 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *FriendsGetUserAvatarResultMessage) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

func init() {
}
