// Code generated by protoc-gen-go.
// source: hello.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type HelloMessage struct {
	Number           *int32  `protobuf:"varint,1,req,name=number" json:"number,omitempty"`
	Number2          *int32  `protobuf:"varint,2,req,name=number2" json:"number2,omitempty"`
	Name             *string `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Stuff            *string `protobuf:"bytes,4,req,name=stuff" json:"stuff,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HelloMessage) Reset()         { *m = HelloMessage{} }
func (m *HelloMessage) String() string { return proto.CompactTextString(m) }
func (*HelloMessage) ProtoMessage()    {}

func (m *HelloMessage) GetNumber() int32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *HelloMessage) GetNumber2() int32 {
	if m != nil && m.Number2 != nil {
		return *m.Number2
	}
	return 0
}

func (m *HelloMessage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *HelloMessage) GetStuff() string {
	if m != nil && m.Stuff != nil {
		return *m.Stuff
	}
	return ""
}

type CloseAppMessage struct {
	Reason           *string `protobuf:"bytes,1,req,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CloseAppMessage) Reset()         { *m = CloseAppMessage{} }
func (m *CloseAppMessage) String() string { return proto.CompactTextString(m) }
func (*CloseAppMessage) ProtoMessage()    {}

func (m *CloseAppMessage) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

type MessagingSendDataMessage struct {
	Npid             *uint64 `protobuf:"fixed64,1,req,name=npid" json:"npid,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MessagingSendDataMessage) Reset()         { *m = MessagingSendDataMessage{} }
func (m *MessagingSendDataMessage) String() string { return proto.CompactTextString(m) }
func (*MessagingSendDataMessage) ProtoMessage()    {}

func (m *MessagingSendDataMessage) GetNpid() uint64 {
	if m != nil && m.Npid != nil {
		return *m.Npid
	}
	return 0
}

func (m *MessagingSendDataMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
}
