// Code generated by protoc-gen-go.
// source: storage.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type StorageGetPublisherFileMessage struct {
	FileName         *string `protobuf:"bytes,1,req,name=fileName" json:"fileName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StorageGetPublisherFileMessage) Reset()         { *m = StorageGetPublisherFileMessage{} }
func (m *StorageGetPublisherFileMessage) String() string { return proto.CompactTextString(m) }
func (*StorageGetPublisherFileMessage) ProtoMessage()    {}

func (m *StorageGetPublisherFileMessage) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

type StoragePublisherFileMessage struct {
	Result           *int32  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	FileName         *string `protobuf:"bytes,2,req,name=fileName" json:"fileName,omitempty"`
	FileData         []byte  `protobuf:"bytes,3,req,name=fileData" json:"fileData,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StoragePublisherFileMessage) Reset()         { *m = StoragePublisherFileMessage{} }
func (m *StoragePublisherFileMessage) String() string { return proto.CompactTextString(m) }
func (*StoragePublisherFileMessage) ProtoMessage()    {}

func (m *StoragePublisherFileMessage) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *StoragePublisherFileMessage) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *StoragePublisherFileMessage) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

type StorageGetUserFileMessage struct {
	FileName         *string `protobuf:"bytes,1,req,name=fileName" json:"fileName,omitempty"`
	Npid             *uint64 `protobuf:"fixed64,2,req,name=npid" json:"npid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StorageGetUserFileMessage) Reset()         { *m = StorageGetUserFileMessage{} }
func (m *StorageGetUserFileMessage) String() string { return proto.CompactTextString(m) }
func (*StorageGetUserFileMessage) ProtoMessage()    {}

func (m *StorageGetUserFileMessage) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *StorageGetUserFileMessage) GetNpid() uint64 {
	if m != nil && m.Npid != nil {
		return *m.Npid
	}
	return 0
}

type StorageUserFileMessage struct {
	Result           *int32  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	FileName         *string `protobuf:"bytes,2,req,name=fileName" json:"fileName,omitempty"`
	Npid             *uint64 `protobuf:"fixed64,3,req,name=npid" json:"npid,omitempty"`
	FileData         []byte  `protobuf:"bytes,4,req,name=fileData" json:"fileData,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StorageUserFileMessage) Reset()         { *m = StorageUserFileMessage{} }
func (m *StorageUserFileMessage) String() string { return proto.CompactTextString(m) }
func (*StorageUserFileMessage) ProtoMessage()    {}

func (m *StorageUserFileMessage) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *StorageUserFileMessage) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *StorageUserFileMessage) GetNpid() uint64 {
	if m != nil && m.Npid != nil {
		return *m.Npid
	}
	return 0
}

func (m *StorageUserFileMessage) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

type StorageWriteUserFileMessage struct {
	FileName         *string `protobuf:"bytes,1,req,name=fileName" json:"fileName,omitempty"`
	Npid             *uint64 `protobuf:"fixed64,2,req,name=npid" json:"npid,omitempty"`
	FileData         []byte  `protobuf:"bytes,3,req,name=fileData" json:"fileData,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StorageWriteUserFileMessage) Reset()         { *m = StorageWriteUserFileMessage{} }
func (m *StorageWriteUserFileMessage) String() string { return proto.CompactTextString(m) }
func (*StorageWriteUserFileMessage) ProtoMessage()    {}

func (m *StorageWriteUserFileMessage) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *StorageWriteUserFileMessage) GetNpid() uint64 {
	if m != nil && m.Npid != nil {
		return *m.Npid
	}
	return 0
}

func (m *StorageWriteUserFileMessage) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

type StorageWriteUserFileResultMessage struct {
	Result           *int32  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	FileName         *string `protobuf:"bytes,2,req,name=fileName" json:"fileName,omitempty"`
	Npid             *uint64 `protobuf:"fixed64,3,req,name=npid" json:"npid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StorageWriteUserFileResultMessage) Reset()         { *m = StorageWriteUserFileResultMessage{} }
func (m *StorageWriteUserFileResultMessage) String() string { return proto.CompactTextString(m) }
func (*StorageWriteUserFileResultMessage) ProtoMessage()    {}

func (m *StorageWriteUserFileResultMessage) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *StorageWriteUserFileResultMessage) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *StorageWriteUserFileResultMessage) GetNpid() uint64 {
	if m != nil && m.Npid != nil {
		return *m.Npid
	}
	return 0
}

type StorageSendRandomStringMessage struct {
	RandomString     *string `protobuf:"bytes,1,req,name=randomString" json:"randomString,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StorageSendRandomStringMessage) Reset()         { *m = StorageSendRandomStringMessage{} }
func (m *StorageSendRandomStringMessage) String() string { return proto.CompactTextString(m) }
func (*StorageSendRandomStringMessage) ProtoMessage()    {}

func (m *StorageSendRandomStringMessage) GetRandomString() string {
	if m != nil && m.RandomString != nil {
		return *m.RandomString
	}
	return ""
}

func init() {
}
